apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: do-sb-onechart-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: do-sb-onechart-demo-app
    environment: ACPT
spec:
  project: default
  destination:
    server: https://bb6ff00d-c3ef-4206-ae4b-c07c036775b1.eu-central-1.linodelke.net
    namespace: default
  sources:
    - chart: onechart
      repoURL: https://chart.onechart.dev
      targetRevision: 0.70.0
      helm:
        valueFiles:
        - $values/values/lke-values.yaml
    - repoURL: https://github.com/rmortale/sb-onechart-demo.git
      ref: values
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      